@startuml
package "PyQt5" {
  [QtCore]
  [QtGui]
  [QtWidgets]
}

[QtCore] --> [Ui_BrickDetector]
[QtGui] --> [Ui_BrickDetector]
[QtWidgets] --> [Ui_BrickDetector]

component "Ui_BrickDetector" {
  [Ui_about_dialog]
  [ImageMode]
}

component "BrickDetector" {
  [ImageMode]
  [Brick]
}

component "utils" {
  [filter_duplicate_coordinates]
}

component "constants" {
  [BLUR_KERNEL]
  [CANNY_MIN]
  [MORTPH_KERNEL]
}

component "model.brick" {
  [Brick]
}

component "model.camera" {
  [ImageMode]
}

component "about" {
  [Ui_about_dialog]
}

[Ui_BrickDetector] --> [BrickDetector]
[BrickDetector] --> [utils]
[BrickDetector] --> [constants]
[BrickDetector] --> [model.brick]
[BrickDetector] --> [model.camera]
[Ui_BrickDetector] --> [about]
@enduml