@startuml
|Main Loop Live|
|Start/End|
|Main Loop Static|

|Start/End|
start
:Benutzer startet die Anwendung;
:Anwendung initialisieren;

:Anwendung läuft Live-Modus;
while (Anwendung beendet?)
if (Benutzereingabe Live oder Static) then (live)

|Main Loop Live|
        :Klemmbaustein-Erkennung;
        :Benutzerinteraktion;
        if (Benutzer klickt auf Trigger) then (Steine erkannt)
            :Liste mit erkannten Klemmbau-\nsteinen wird ausgegeben;
            else (keine Steine erkannt)
            :leere Liste wird ausgegeben;
        endif

else (static)
|Main Loop Static|
        :Anwendung läuft Static-Modus;
        :Klemmbaustein-Erkennung;
        if (Steine erkannt) then (ja)
            :Liste mit erkannten Klemmbau-\nsteinen wird ausgegeben;
            else (nein)
            :leere Liste wird ausgegeben;
        endif
endif
end while
|Start/End|
:Anwendung beenden;
stop
@enduml
